import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar/NavBar";
import { ThemeProvider } from "./components/theme-provider";
import GenreCard from "./components/NavBar/GenreCard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          <GenreCard name="aivnoriwn" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
